#!/bin/sh

#
# This script will load 'alrandom' module. The module will create 
# device /dev/alrandom that can be used to read the random bytes
# generated by AlphaRNG device. Device file /dev/alrandom will
# initially be created with ROOT access permissions. 
# To add public read access to the /dev/alrandom device just 
# copy 80-alphartng-device-access.rules file to /etc/udev/rules.d/
# directory.
#
module=alrandom

insmod ./$module.ko $* || exit 1
echo "Module $module loaded"

